version: '{build}'
environment:
  global:
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd'
  matrix:
  - PYTHON: "C:\\Python35"
    PYTHON_VERSION: "3.5.4"
    PYTHON_ARCH: "32"
  - PYTHON: "C:\\Python35-x64"
    PYTHON_VERSION: "3.5.4"
    PYTHON_ARCH: "64"
  - PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.8"
    PYTHON_ARCH: "64"
  - PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7.4"
    PYTHON_ARCH: "64"
install:
- SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
- python --version
- python -c "import struct; print(struct.calcsize('P') * 8)"
- '%CMD_IN_ENV% python -m pip install --upgrade setuptools pip wheel'
- '%CMD_IN_ENV% python -m pip wheel --find-links=C:\wheelhouse -r requirements.txt --wheel-dir=C:\wheelhouse'
- '%CMD_IN_ENV% python -m pip install --find-links=C:\wheelhouse -r requirements.txt'
cache: C:\wheelhouse
build: off
test_script:
- '%CMD_IN_ENV% python -m pytest fuselage'
